# Configuração de build que executa nosso script customizado
[build]
  # CORREÇÃO CRÍTICA: Executa o script "build" do package.json
  command = "npm run build"
  functions = "netlify/functions"

# Configuração específica para as funções, mantendo o empacotador 'nft'
[functions]
  node_bundler = "nft"

# A regra de redirecionamento permanece a mesma.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
