# Define o diretório onde as suas funções serverless estão localizadas.
[build]
  functions = "netlify/functions"

# Redireciona a chamada para /hello para a nossa função hello.js
[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200
