# Configuração de build que aponta para o diretório das funções.
[build]
  functions = "netlify/functions"

# Redireciona qualquer chamada para /api/... para a nossa função scraper.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/scraper/:splat"
  status = 200
